### ISSUE TITLE
Needs test

### ISSUE THREAD

**Issue by bdougie** [americool/vndr_ideas#8]
I realized that e have covered this, and I doubt it is covered in the Udemy course you are doing.

Making this issue so I don't forget to mention this Monday.

**Comment by americool** [comment]
This is a good point, and an area I'm fairly weak so it's good to work on. I haven't gotten much done on the app because I've been digging deeper into the udemy course as I was having trouble setting up the navigation and understanding how that's all supposed to work and it's covered in a later section. Should be all finished with that by Monday and we can talk about it.
